// <auto-generated />
namespace LyricsGame.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addLyrics : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addLyrics));
        
        string IMigrationMetadata.Id
        {
            get { return "201210292004111_addLyrics"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
