// <auto-generated />
namespace LyricsGame.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class userSegmentVotes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userSegmentVotes));
        
        string IMigrationMetadata.Id
        {
            get { return "201212031057143_userSegmentVotes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
