// <auto-generated />
namespace LyricsGame.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class flagHandling : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(flagHandling));
        
        string IMigrationMetadata.Id
        {
            get { return "201211250529522_flagHandling"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
